//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M06 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoM06 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoM06() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M06.RecursoM06", typeof(RecursoM06).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @com_descripcion.
        /// </summary>
        internal static string com_descripcion {
            get {
                return ResourceManager.GetString("com_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @com_estatus.
        /// </summary>
        internal static string com_estatus {
            get {
                return ResourceManager.GetString("com_estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @com_nombre.
        /// </summary>
        internal static string com_nombre {
            get {
                return ResourceManager.GetString("com_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @com_tipo.
        /// </summary>
        internal static string com_tipo {
            get {
                return ResourceManager.GetString("com_tipo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to com_vue_id.
        /// </summary>
        internal static string com_vue_id
        {
            get
            {
                return ResourceManager.GetString("com_vue_id", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to @com_vue_id.
        /// </summary>
        internal static string com_vue_id_insertar
        {
            get
            {
                return ResourceManager.GetString("@com_vue_id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to @vue_codigo.
        /// </summary>
        internal static string vue_codigo
        {
            get
            {
                return ResourceManager.GetString("vue_codigo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to com_vue_cantidad.
        /// </summary>
        internal static string com_vue_cantidad
        {
            get
            {
                return ResourceManager.GetString("com_vue_cantidad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to @com_vue_cantidad.
        /// </summary>
        internal static string com_vue_cantidad_insertar
        {
            get
            {
                return ResourceManager.GetString("@com_vue_cantidad", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to @com_nombre_consultar.
        /// </summary>
        internal static string com_nombre_consultar
        {
            get
            {
                return ResourceManager.GetString("com_nombre_consultar", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to @com_tipo_consultar.
        /// </summary>
        internal static string com_tipo_consultar
        {
            get
            {
                return ResourceManager.GetString("com_tipo_consultar", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to @com_estatus_consultar.
        /// </summary>
        internal static string com_estatus_consultar
        {
            get
            {
                return ResourceManager.GetString("com_estatus_consultar", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to @com_descripcion_consultar.
        /// </summary>
        internal static string com_descripcion_consultar
        {
            get
            {
                return ResourceManager.GetString("com_descripcion_consultar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to M06_AgregarComida.
        /// </summary>
        internal static string procedimientoAgregarComida {
            get {
                return ResourceManager.GetString("procedimientoAgregarComida", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to M06_AgregarComidaVuelo.
        /// </summary>
        internal static string procedimientoAgregarComidaVuelo
        {
            get
            {
                return ResourceManager.GetString("procedimientoAgregarComidaVuelo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to M06_ConsultarComidas.
        /// </summary>
        internal static string procedimientoConsultarComidas{
            get
            {
                return ResourceManager.GetString("procedimientoConsultarComidas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to M06_ConsultarComidasVuelos.
        /// </summary>
        internal static string procedimientoConsultarComidasVuelos
        {
            get
            {
                return ResourceManager.GetString("procedimientoConsultarComidasVuelos", resourceCulture);
            }
        }

    }
}
