//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M04 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoVuelo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoVuelo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M04.RecursoVuelo", typeof(RecursoVuelo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M04_BuscarAvionRuta.
        /// </summary>
        internal static string BuscarAvionRuta {
            get {
                return ResourceManager.GetString("BuscarAvionRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M04_BuscarCodigo.
        /// </summary>
        internal static string BuscarCodigo {
            get {
                return ResourceManager.GetString("BuscarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M04_BuscaVuelo.
        /// </summary>
        internal static string BuscaVueloID {
            get {
                return ResourceManager.GetString("BuscaVueloID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M04_CambiarStatus.
        /// </summary>
        internal static string CambiarStatus {
            get {
                return ResourceManager.GetString("CambiarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M04_CrearVuelo.
        /// </summary>
        internal static string CrearVuelo {
            get {
                return ResourceManager.GetString("CrearVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M04_EliminarVuelo.
        /// </summary>
        internal static string EliminarVuelo {
            get {
                return ResourceManager.GetString("EliminarVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay aviones disponibles para cubrir la ruta seleccionada.
        /// </summary>
        internal static string ErrorAvionRuta {
            get {
                return ResourceManager.GetString("ErrorAvionRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos Obligatorios Vacios.
        /// </summary>
        internal static string ErrorCampoVacio {
            get {
                return ResourceManager.GetString("ErrorCampoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El codigo de vuelo ya se encuentra registrado.
        /// </summary>
        internal static string ErrorCodigoDuplicado {
            get {
                return ResourceManager.GetString("ErrorCodigoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reserva-404.
        /// </summary>
        internal static string ErrorDaoVuelo {
            get {
                return ResourceManager.GetString("ErrorDaoVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la conexión con la Base de Datos.
        /// </summary>
        internal static string ErrorGeneralBD {
            get {
                return ResourceManager.GetString("ErrorGeneralBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argumento nulo.
        /// </summary>
        internal static string ErrorMensajeArgumento {
            get {
                return ResourceManager.GetString("ErrorMensajeArgumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: Existen registros asociados a este vuelo.
        /// </summary>
        internal static string ErrorMensajeDependencia {
            get {
                return ResourceManager.GetString("ErrorMensajeDependencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato invalido.
        /// </summary>
        internal static string ErrorMensajeFormato {
            get {
                return ResourceManager.GetString("ErrorMensajeFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M04_CalcularFechaAterrizaje.
        /// </summary>
        internal static string FechaAterrizaje {
            get {
                return ResourceManager.GetString("FechaAterrizaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M04_ListarLugarD.
        /// </summary>
        internal static string ListarLugarD {
            get {
                return ResourceManager.GetString("ListarLugarD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M04_ListarLugarO.
        /// </summary>
        internal static string ListarLugarO {
            get {
                return ResourceManager.GetString("ListarLugarO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M04_ListarVuelos.
        /// </summary>
        internal static string ListarVuelos {
            get {
                return ResourceManager.GetString("ListarVuelos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M04_ModificarVuelo.
        /// </summary>
        internal static string ModificarVuelo {
            get {
                return ResourceManager.GetString("ModificarVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aMatricula.
        /// </summary>
        internal static string ParametroaAMatricula {
            get {
                return ResourceManager.GetString("ParametroaAMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aModelo.
        /// </summary>
        internal static string ParametroAModelo {
            get {
                return ResourceManager.GetString("ParametroAModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a capEje.
        /// </summary>
        internal static string ParametroCapacidadEjecutiva {
            get {
                return ResourceManager.GetString("ParametroCapacidadEjecutiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aCapMax.
        /// </summary>
        internal static string ParametroCapacidadMaxima {
            get {
                return ResourceManager.GetString("ParametroCapacidadMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a capTur.
        /// </summary>
        internal static string ParametroCapacidadTurista {
            get {
                return ResourceManager.GetString("ParametroCapacidadTurista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a capVip.
        /// </summary>
        internal static string ParametroCapacidadVIP {
            get {
                return ResourceManager.GetString("ParametroCapacidadVIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cDestino.
        /// </summary>
        internal static string ParametroCDestino {
            get {
                return ResourceManager.GetString("ParametroCDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a codVuelo.
        /// </summary>
        internal static string ParametroCodVuelo {
            get {
                return ResourceManager.GetString("ParametroCodVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cOrigen.
        /// </summary>
        internal static string ParametroCOrigen {
            get {
                return ResourceManager.GetString("ParametroCOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aDistMax.
        /// </summary>
        internal static string ParametroDistMaxima {
            get {
                return ResourceManager.GetString("ParametroDistMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaAterrizajeVuelo.
        /// </summary>
        internal static string ParametroFechaAterrizaje {
            get {
                return ResourceManager.GetString("ParametroFechaAterrizaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaDespegueVuelo.
        /// </summary>
        internal static string ParametroFechaDespegue {
            get {
                return ResourceManager.GetString("ParametroFechaDespegue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idAvion.
        /// </summary>
        internal static string ParametroIdAvion {
            get {
                return ResourceManager.GetString("ParametroIdAvion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idDestino.
        /// </summary>
        internal static string ParametroIdDestino {
            get {
                return ResourceManager.GetString("ParametroIdDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idOrigen.
        /// </summary>
        internal static string ParametroIdOrigen {
            get {
                return ResourceManager.GetString("ParametroIdOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idRuta.
        /// </summary>
        internal static string ParametroIdRuta {
            get {
                return ResourceManager.GetString("ParametroIdRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idVuelo.
        /// </summary>
        internal static string ParametroIdVuelo {
            get {
                return ResourceManager.GetString("ParametroIdVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a statusVuelo.
        /// </summary>
        internal static string ParametroStatus {
            get {
                return ResourceManager.GetString("ParametroStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aVelMax.
        /// </summary>
        internal static string ParametroVelMaxima {
            get {
                return ResourceManager.GetString("ParametroVelMaxima", resourceCulture);
            }
        }
    }
}
