//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M04 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoVuelo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoVuelo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M04.RecursoVuelo", typeof(RecursoVuelo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a codVuelo.
        /// </summary>
        internal static string codVuelo {
            get {
                return ResourceManager.GetString("codVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaAterrizajeVuelo.
        /// </summary>
        internal static string fechaAterrizaje {
            get {
                return ResourceManager.GetString("fechaAterrizaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaDespegueVuelo.
        /// </summary>
        internal static string fechaDespegue {
            get {
                return ResourceManager.GetString("fechaDespegue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idAvion.
        /// </summary>
        internal static string idAvion {
            get {
                return ResourceManager.GetString("idAvion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idRuta.
        /// </summary>
        internal static string idRuta {
            get {
                return ResourceManager.GetString("idRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idVuelo.
        /// </summary>
        internal static string idVuelo {
            get {
                return ResourceManager.GetString("idVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M04_ListarVuelos.
        /// </summary>
        internal static string ListarVuelos {
            get {
                return ResourceManager.GetString("ListarVuelos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a statusVuelo.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
    }
}
