
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.Models.gestion_cruceros {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosCruceros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosCruceros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.Models.gestion_cruceros.RecursosCruceros", typeof(RecursosCruceros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M24_AgregarCabinas.
        /// </summary>
        internal static string AgregarCabinas {
            get {
                return ResourceManager.GetString("AgregarCabinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M24_AgregarCamarote.
        /// </summary>
        internal static string AgregarCamarote {
            get {
                return ResourceManager.GetString("AgregarCamarote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M24_AgregarCrucero.
        /// </summary>
        internal static string AgregarCruceros {
            get {
                return ResourceManager.GetString("AgregarCruceros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M24_AgregarItinerario.
        /// </summary>
        internal static string AgregarItinerario {
            get {
                return ResourceManager.GetString("AgregarItinerario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M24_CambiarEstatusCabina.
        /// </summary>
        internal static string CambioEstatusCabinas {
            get {
                return ResourceManager.GetString("CambioEstatusCabinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M24_CambiarEstatusCamarote.
        /// </summary>
        internal static string CambioEstatusCamarote {
            get {
                return ResourceManager.GetString("CambioEstatusCamarote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M24_CambiarEstatusCrucero.
        /// </summary>
        internal static string CambioEstatusCrucero {
            get {
                return ResourceManager.GetString("CambioEstatusCrucero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M24_EliminarCruceros.
        /// </summary>
        internal static string EliminarCruceros {
            get {
                return ResourceManager.GetString("EliminarCruceros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M24_ListarCabinas.
        /// </summary>
        internal static string ListarCabinas {
            get {
                return ResourceManager.GetString("ListarCabinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M24_ListarCamarote.
        /// </summary>
        internal static string ListarCamarote {
            get {
                return ResourceManager.GetString("ListarCamarote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M24_ListarCruceros.
        /// </summary>
        internal static string ListarCruceros {
            get {
                return ResourceManager.GetString("ListarCruceros", resourceCulture);
            }
        }
    }
}

