//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M01 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoLogin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M01.RecursoLogin", typeof(RecursoLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M01_ActivarUsuario.
        /// </summary>
        internal static string ActivarUsuario {
            get {
                return ResourceManager.GetString("ActivarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M01_DesactivarUsuario.
        /// </summary>
        internal static string BloquearUsuario {
            get {
                return ResourceManager.GetString("BloquearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M01_ConsultarUsuario.
        /// </summary>
        internal static string ConsultarUsuario {
            get {
                return ResourceManager.GetString("ConsultarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @correo.
        /// </summary>
        internal static string correo {
            get {
                return ResourceManager.GetString("correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M01_EliminarLogin.
        /// </summary>
        internal static string EliminarLogin {
            get {
                return ResourceManager.GetString("EliminarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M01_IncrementarIntentos.
        /// </summary>
        internal static string IncrementarIntentos {
            get {
                return ResourceManager.GetString("IncrementarIntentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M01_InsertarLogin.
        /// </summary>
        internal static string InsertarLogin {
            get {
                return ResourceManager.GetString("InsertarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M01_NumeroIntentos.
        /// </summary>
        internal static string NumeroIntentos {
            get {
                return ResourceManager.GetString("NumeroIntentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M01_ResetearIntentos.
        /// </summary>
        internal static string ResetearIntentos {
            get {
                return ResourceManager.GetString("ResetearIntentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activo.
        /// </summary>
        internal static string usuarioActivo {
            get {
                return ResourceManager.GetString("usuarioActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apellido.
        /// </summary>
        internal static string usuarioApellido {
            get {
                return ResourceManager.GetString("usuarioApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contrasena.
        /// </summary>
        internal static string usuarioClave {
            get {
                return ResourceManager.GetString("usuarioClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to correo.
        /// </summary>
        internal static string usuarioCorreo {
            get {
                return ResourceManager.GetString("usuarioCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fecha.
        /// </summary>
        internal static string usuarioFechaCreacion {
            get {
                return ResourceManager.GetString("usuarioFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuID.
        /// </summary>
        internal static string usuarioID {
            get {
                return ResourceManager.GetString("usuarioID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rolID.
        /// </summary>
        internal static string usuarioIDRol {
            get {
                return ResourceManager.GetString("usuarioIDRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre.
        /// </summary>
        internal static string usuarioNombre {
            get {
                return ResourceManager.GetString("usuarioNombre", resourceCulture);
            }
        }
    }
}
