<<<<<<< HEAD
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M07 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class M07Equipaje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M07Equipaje() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M07.M07Equipaje", typeof(M07Equipaje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @equ_fk_pase_abordaje.
        /// </summary>
        internal static string equ_fk_pase_abordaje {
            get {
                return ResourceManager.GetString("equ_fk_pase_abordaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @equ_id.
        /// </summary>
        internal static string equ_id {
            get {
                return ResourceManager.GetString("equ_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @equ_peso.
        /// </summary>
        internal static string equ_peso {
            get {
                return ResourceManager.GetString("equ_peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equ_fk_pase_abordaje.
        /// </summary>
        internal static string equFkPaseAbordaje {
            get {
                return ResourceManager.GetString("equFkPaseAbordaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equ_id.
        /// </summary>
        internal static string equID {
            get {
                return ResourceManager.GetString("equID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equ_peso.
        /// </summary>
        internal static string equPeso {
            get {
                return ResourceManager.GetString("equPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_AgregarEquipaje.
        /// </summary>
        internal static string procedimientoAgregarEquipaje {
            get {
                return ResourceManager.GetString("procedimientoAgregarEquipaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_ConsultarEquipaje.
        /// </summary>
        internal static string procedimientoConsultarEquipaje {
            get {
                return ResourceManager.GetString("procedimientoConsultarEquipaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_ConsultarEquipajePorAbordaje.
        /// </summary>
        internal static string procedimientoConsultarEquipajePorAbordaje {
            get {
                return ResourceManager.GetString("procedimientoConsultarEquipajePorAbordaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_ConsultarEquipajePorID.
        /// </summary>
        internal static string procedimientoConsultarEquipajePorID {
            get {
                return ResourceManager.GetString("procedimientoConsultarEquipajePorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_EditarEquipaje.
        /// </summary>
        internal static string procedimientoEditarEquipaje {
            get {
                return ResourceManager.GetString("procedimientoEditarEquipaje", resourceCulture);
            }
        }
    }
}
=======
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M07 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class M07Equipaje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M07Equipaje() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M07.M07Equipaje", typeof(M07Equipaje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_AgregarEquipaje.
        /// </summary>
        internal static string procedimientoAgregarEquipaje {
            get {
                return ResourceManager.GetString("procedimientoAgregarEquipaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_ConsultarEquipaje.
        /// </summary>
        internal static string procedimientoConsultarEquipaje {
            get {
                return ResourceManager.GetString("procedimientoConsultarEquipaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_ConsultarEquipajePorAbordaje.
        /// </summary>
        internal static string procedimientoConsultarEquipajePorAbordaje {
            get {
                return ResourceManager.GetString("procedimientoConsultarEquipajePorAbordaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_ConsultarEquipajePorID.
        /// </summary>
        internal static string procedimientoConsultarEquipajePorID {
            get {
                return ResourceManager.GetString("procedimientoConsultarEquipajePorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_EditarEquipaje.
        /// </summary>
        internal static string procedimientoEditarEquipaje {
            get {
                return ResourceManager.GetString("procedimientoEditarEquipaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rec_descripcion.
        /// </summary>
        internal static string rec_descripcion {
            get {
                return ResourceManager.GetString("rec_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rec_fecha.
        /// </summary>
        internal static string rec_fecha {
            get {
                return ResourceManager.GetString("rec_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rec_fk_equipaje.
        /// </summary>
        internal static string rec_fk_equipaje {
            get {
                return ResourceManager.GetString("rec_fk_equipaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rec_fk_pasajero.
        /// </summary>
        internal static string rec_fk_pasajero {
            get {
                return ResourceManager.GetString("rec_fk_pasajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rec_id.
        /// </summary>
        internal static string rec_id {
            get {
                return ResourceManager.GetString("rec_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rec_status.
        /// </summary>
        internal static string rec_status {
            get {
                return ResourceManager.GetString("rec_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec_descripcion.
        /// </summary>
        internal static string recDescripcion {
            get {
                return ResourceManager.GetString("recDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec_fecha.
        /// </summary>
        internal static string recFecha {
            get {
                return ResourceManager.GetString("recFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec_fk_equipaje.
        /// </summary>
        internal static string recFkEquipaje {
            get {
                return ResourceManager.GetString("recFkEquipaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec_fk_pasajero.
        /// </summary>
        internal static string recFkPasajero {
            get {
                return ResourceManager.GetString("recFkPasajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec_id.
        /// </summary>
        internal static string recId {
            get {
                return ResourceManager.GetString("recId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec_status.
        /// </summary>
        internal static string recStatus {
            get {
                return ResourceManager.GetString("recStatus", resourceCulture);
            }
        }
    }
}
>>>>>>> 5a804a8964716697a561d6fc1af99c730997e606
