//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M07 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class M07ReclamoEquipaje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M07ReclamoEquipaje() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M07.M07ReclamoEquipaje", typeof(M07ReclamoEquipaje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_AgregarReclamo.
        /// </summary>
        internal static string procedimientoAgregarReclamo {
            get {
                return ResourceManager.GetString("procedimientoAgregarReclamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_ConsultarReclamoPorEquipaje.
        /// </summary>
        internal static string procedimientoConsultarReclamoPorEquipaje {
            get {
                return ResourceManager.GetString("procedimientoConsultarReclamoPorEquipaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_ConsultarReclamoPorID.
        /// </summary>
        internal static string procedimientoConsultarReclamoPorID {
            get {
                return ResourceManager.GetString("procedimientoConsultarReclamoPorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_ConsultarReclamoPorPasajero.
        /// </summary>
        internal static string procedimientoConsultarReclamoPorPasajero {
            get {
                return ResourceManager.GetString("procedimientoConsultarReclamoPorPasajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_EditarReclamo.
        /// </summary>
        internal static string procedimientoEditarReclamo {
            get {
                return ResourceManager.GetString("procedimientoEditarReclamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M07_EditarReclamoEstado.
        /// </summary>
        internal static string procedimientoEditarReclamoEstado {
            get {
                return ResourceManager.GetString("procedimientoEditarReclamoEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rec_descripcion.
        /// </summary>
        internal static string rec_descripcion {
            get {
                return ResourceManager.GetString("rec_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rec_fecha.
        /// </summary>
        internal static string rec_fecha {
            get {
                return ResourceManager.GetString("rec_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rec_fk_equipaje.
        /// </summary>
        internal static string rec_fk_equipaje {
            get {
                return ResourceManager.GetString("rec_fk_equipaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rec_fk_pasajero.
        /// </summary>
        internal static string rec_fk_pasajero {
            get {
                return ResourceManager.GetString("rec_fk_pasajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rec_id.
        /// </summary>
        internal static string rec_id {
            get {
                return ResourceManager.GetString("rec_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rec_status.
        /// </summary>
        internal static string rec_status {
            get {
                return ResourceManager.GetString("rec_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec_descripcion.
        /// </summary>
        internal static string recDescripcion {
            get {
                return ResourceManager.GetString("recDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec_fecha.
        /// </summary>
        internal static string recFecha {
            get {
                return ResourceManager.GetString("recFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec_fk_equipaje.
        /// </summary>
        internal static string recFkEquipaje {
            get {
                return ResourceManager.GetString("recFkEquipaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec_fk_pasajero.
        /// </summary>
        internal static string recFkPasajero {
            get {
                return ResourceManager.GetString("recFkPasajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec_id.
        /// </summary>
        internal static string recId {
            get {
                return ResourceManager.GetString("recId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rec_status.
        /// </summary>
        internal static string recStatus {
            get {
                return ResourceManager.GetString("recStatus", resourceCulture);
            }
        }
    }
}
