//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M09 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM09 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM09() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M09.RecursoDAOM09", typeof(RecursoDAOM09).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @hot_cantidad_habitaciones.
        /// </summary>
        internal static string hot_cantidad_habitaciones {
            get {
                return ResourceManager.GetString("hot_cantidad_habitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @hot_direccion.
        /// </summary>
        internal static string hot_direccion {
            get {
                return ResourceManager.GetString("hot_direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @hot_disponible.
        /// </summary>
        internal static string hot_disponible {
            get {
                return ResourceManager.GetString("hot_disponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @hot_email.
        /// </summary>
        internal static string hot_email {
            get {
                return ResourceManager.GetString("hot_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @hot_estrellas.
        /// </summary>
        internal static string hot_estrellas {
            get {
                return ResourceManager.GetString("hot_estrellas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @hot_fk_ciudad.
        /// </summary>
        internal static string hot_fk_ciudad {
            get {
                return ResourceManager.GetString("hot_fk_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @hot_id.
        /// </summary>
        internal static string hot_id {
            get {
                return ResourceManager.GetString("hot_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @hot_nombre.
        /// </summary>
        internal static string hot_nombre {
            get {
                return ResourceManager.GetString("hot_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @hot_pagina.
        /// </summary>
        internal static string hot_pagina {
            get {
                return ResourceManager.GetString("hot_pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_ciudad.
        /// </summary>
        internal static string id_ciudad {
            get {
                return ResourceManager.GetString("id_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_pais.
        /// </summary>
        internal static string id_pais {
            get {
                return ResourceManager.GetString("id_pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre_ciudad.
        /// </summary>
        internal static string nombre_ciudad {
            get {
                return ResourceManager.GetString("nombre_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre_pais.
        /// </summary>
        internal static string nombre_pais {
            get {
                return ResourceManager.GetString("nombre_pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M09_AgregarHotel.
        /// </summary>
        internal static string ProcedimientoAgregarHotel {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M09_CambiarStatusHotel.
        /// </summary>
        internal static string ProcedimientoCambiarDisponibilidad {
            get {
                return ResourceManager.GetString("ProcedimientoCambiarDisponibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M09_ConsultarHotel.
        /// </summary>
        internal static string ProcedimientoConsultarHotel {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M09_ConsultarHoteles.
        /// </summary>
        internal static string ProcedimientoConsultarTodos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M09_EliminarHotel.
        /// </summary>
        internal static string ProcedimientoEliminarHotel {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M09_ModificarHotel.
        /// </summary>
        internal static string ProcedimientoModificarHotel {
            get {
                return ResourceManager.GetString("ProcedimientoModificarHotel", resourceCulture);
            }
        }
    }
}
