//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M16 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class M16Reclamos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M16Reclamos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M16.M16Reclamos", typeof(M16Reclamos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M16_ActualizarReclamo.
        /// </summary>
        internal static string procedimientoActualizarReclamo {
            get {
                return ResourceManager.GetString("procedimientoActualizarReclamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M16_ConsultarReclamos.
        /// </summary>
        internal static string procedimientoActualizarReclamprocedimientoConsultarReclamos {
            get {
                return ResourceManager.GetString("procedimientoActualizarReclamprocedimientoConsultarReclamos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M16_AgregarReclamo.
        /// </summary>
        internal static string procedimientoAgregarReclamo {
            get {
                return ResourceManager.GetString("procedimientoAgregarReclamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M16_ConsultarReclamosPorId.
        /// </summary>
        internal static string procedimientoConsultarReclamoPorId {
            get {
                return ResourceManager.GetString("procedimientoConsultarReclamoPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M16_ConsultarReclamos.
        /// </summary>
        internal static string procedimientoConsultarReclamos {
            get {
                return ResourceManager.GetString("procedimientoConsultarReclamos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M16_ConsultarReclamosPorUsuario.
        /// </summary>
        internal static string procedimientoConsultarReclamosUsuario {
            get {
                return ResourceManager.GetString("procedimientoConsultarReclamosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M16_EliminarReclamo.
        /// </summary>
        internal static string procedimientoEliminarReclamo {
            get {
                return ResourceManager.GetString("procedimientoEliminarReclamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M16_ModificarReclamo.
        /// </summary>
        internal static string procedimientoModificarReclamo {
            get {
                return ResourceManager.GetString("procedimientoModificarReclamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rec_descripcion.
        /// </summary>
        internal static string rec_descripcion {
            get {
                return ResourceManager.GetString("rec_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rec_estatus.
        /// </summary>
        internal static string rec_estatus {
            get {
                return ResourceManager.GetString("rec_estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rec_fecha.
        /// </summary>
        internal static string rec_fecha {
            get {
                return ResourceManager.GetString("rec_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rec_fk_usuario.
        /// </summary>
        internal static string rec_fk_usuario {
            get {
                return ResourceManager.GetString("rec_fk_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rec_id.
        /// </summary>
        internal static string rec_id {
            get {
                return ResourceManager.GetString("rec_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rec_titulo.
        /// </summary>
        internal static string rec_titulo {
            get {
                return ResourceManager.GetString("rec_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rec_descripcion.
        /// </summary>
        internal static string recDescripcion {
            get {
                return ResourceManager.GetString("recDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rec_estatus.
        /// </summary>
        internal static string recEstatus {
            get {
                return ResourceManager.GetString("recEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rec_fecha.
        /// </summary>
        internal static string recFecha {
            get {
                return ResourceManager.GetString("recFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rec_fk_usuario.
        /// </summary>
        internal static string recFkUsuario {
            get {
                return ResourceManager.GetString("recFkUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rec_id.
        /// </summary>
        internal static string recId {
            get {
                return ResourceManager.GetString("recId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rec_titulo.
        /// </summary>
        internal static string rectitulo {
            get {
                return ResourceManager.GetString("rectitulo", resourceCulture);
            }
        }
    }
}
