//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.Models.gestion_usuarios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoBD {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoBD() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.Models.gestion_usuarios.RecursoBD", typeof(RecursoBD).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva_BD_1.
        /// </summary>
        internal static string Cod_Error_Conexion {
            get {
                return ResourceManager.GetString("Cod_Error_Conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva_BD_3.
        /// </summary>
        internal static string Cod_Error_Desconexion {
            get {
                return ResourceManager.GetString("Cod_Error_Desconexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva_BD_0.
        /// </summary>
        internal static string Cod_Error_General {
            get {
                return ResourceManager.GetString("Cod_Error_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva_BD_2.
        /// </summary>
        internal static string Cod_Error_Parametro {
            get {
                return ResourceManager.GetString("Cod_Error_Parametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo establecer una conexión con el servidor de datos.
        /// </summary>
        internal static string Error_Conexion {
            get {
                return ResourceManager.GetString("Error_Conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al cerrar la conexión con el servidor de datos.
        /// </summary>
        internal static string Error_Desconexión {
            get {
                return ResourceManager.GetString("Error_Desconexión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo completar la operación.
        /// </summary>
        internal static string Error_General {
            get {
                return ResourceManager.GetString("Error_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la ejecución de un stored procedure debido a un parametro.
        /// </summary>
        internal static string Error_Parametro {
            get {
                return ResourceManager.GetString("Error_Parametro", resourceCulture);
            }
        }
    }
}
