//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.Models.gestion_usuarios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoUsuario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoUsuario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.Models.gestion_usuarios.RecursoUsuario", typeof(RecursoUsuario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activo.
        /// </summary>
        internal static string ActivoUsuario {
            get {
                return ResourceManager.GetString("ActivoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apellido.
        /// </summary>
        internal static string ApellidoUsuario {
            get {
                return ResourceManager.GetString("ApellidoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha ingresado un argumento con un valor invalido.
        /// </summary>
        internal static string ArgumentoInvalido {
            get {
                return ResourceManager.GetString("ArgumentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de conexión con la base de datos.
        /// </summary>
        internal static string BDError {
            get {
                return ResourceManager.GetString("BDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M12_ConsultarUsuario.
        /// </summary>
        internal static string ConsultarEmail {
            get {
                return ResourceManager.GetString("ConsultarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M12_ConsultarUsuarioID.
        /// </summary>
        internal static string ConsultarID {
            get {
                return ResourceManager.GetString("ConsultarID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to correo.
        /// </summary>
        internal static string CorreoUsuario {
            get {
                return ResourceManager.GetString("CorreoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M12_CrearUsuario.
        /// </summary>
        internal static string CrearUsuario {
            get {
                return ResourceManager.GetString("CrearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M12_EliminarUsuario.
        /// </summary>
        internal static string EliminarUsuario {
            get {
                return ResourceManager.GetString("EliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, el correo introducido ya se encuentra registrado.
        /// </summary>
        internal static string Error_Email_Existe {
            get {
                return ResourceManager.GetString("Error_Email_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva_M12.
        /// </summary>
        internal static string ExceptionM12 {
            get {
                return ResourceManager.GetString("ExceptionM12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fecha.
        /// </summary>
        internal static string FechaUsuario {
            get {
                return ResourceManager.GetString("FechaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha ingresado datos con un formato invalido.
        /// </summary>
        internal static string FormatoInvalido {
            get {
                return ResourceManager.GetString("FormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuID.
        /// </summary>
        internal static string IDUsuario {
            get {
                return ResourceManager.GetString("IDUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M12_ListarUsuarios.
        /// </summary>
        internal static string ListarUsuarios {
            get {
                return ResourceManager.GetString("ListarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M12_ModificarUsuario.
        /// </summary>
        internal static string ModificarUsuario {
            get {
                return ResourceManager.GetString("ModificarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre.
        /// </summary>
        internal static string NombreUsuario {
            get {
                return ResourceManager.GetString("NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al momento de realizar la operación.
        /// </summary>
        internal static string OtroError {
            get {
                return ResourceManager.GetString("OtroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @activo.
        /// </summary>
        internal static string ParametroActivo {
            get {
                return ResourceManager.GetString("ParametroActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @apellido.
        /// </summary>
        internal static string ParametroApellido {
            get {
                return ResourceManager.GetString("ParametroApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @contraseña.
        /// </summary>
        internal static string ParametroContraseña {
            get {
                return ResourceManager.GetString("ParametroContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @correo.
        /// </summary>
        internal static string ParametroCorreo {
            get {
                return ResourceManager.GetString("ParametroCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fecha.
        /// </summary>
        internal static string ParametroFecha {
            get {
                return ResourceManager.GetString("ParametroFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id.
        /// </summary>
        internal static string ParametroID {
            get {
                return ResourceManager.GetString("ParametroID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombre.
        /// </summary>
        internal static string ParametroNombre {
            get {
                return ResourceManager.GetString("ParametroNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rol.
        /// </summary>
        internal static string ParametroRolID {
            get {
                return ResourceManager.GetString("ParametroRolID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rolID.
        /// </summary>
        internal static string RolIDUsuario {
            get {
                return ResourceManager.GetString("RolIDUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rol.
        /// </summary>
        internal static string RolUsuario {
            get {
                return ResourceManager.GetString("RolUsuario", resourceCulture);
            }
        }
    }
}
