//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.Models.gestion_usuarios {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoUsuario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoUsuario() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.Models.gestion_usuarios.RecursoUsuario", typeof(RecursoUsuario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a activo.
        /// </summary>
        internal static string ActivoUsuario {
            get {
                return ResourceManager.GetString("ActivoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a apellido.
        /// </summary>
        internal static string ApellidoUsuario {
            get {
                return ResourceManager.GetString("ApellidoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha ingresado un argumento con un _idHotel invalido.
        /// </summary>
        internal static string ArgumentoInvalido {
            get {
                return ResourceManager.GetString("ArgumentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexion con la base de datos.
        /// </summary>
        internal static string BDError {
            get {
                return ResourceManager.GetString("BDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_CambiarStatus.
        /// </summary>
        internal static string CambiarStatus {
            get {
                return ResourceManager.GetString("CambiarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_ConsultarUsuario.
        /// </summary>
        internal static string ConsultarEmail {
            get {
                return ResourceManager.GetString("ConsultarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_ConsultarUsuarioID.
        /// </summary>
        internal static string ConsultarID {
            get {
                return ResourceManager.GetString("ConsultarID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_ConsultarUltimoUsuarioID.
        /// </summary>
        internal static string ConsultarIDUltimo {
            get {
                return ResourceManager.GetString("ConsultarIDUltimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_ContarUsuario.
        /// </summary>
        internal static string ContarUsuario {
            get {
                return ResourceManager.GetString("ContarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a correo.
        /// </summary>
        internal static string CorreoUsuario {
            get {
                return ResourceManager.GetString("CorreoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_CrearUsuario.
        /// </summary>
        internal static string CrearUsuario {
            get {
                return ResourceManager.GetString("CrearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_EliminarUsuario.
        /// </summary>
        internal static string EliminarUsuario {
            get {
                return ResourceManager.GetString("EliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: Debe existir al menos un usuario Administrador Activo.
        /// </summary>
        internal static string Error_Activo {
            get {
                return ResourceManager.GetString("Error_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: El usuario no se puede eliminar ya que tiene registros asociados.
        /// </summary>
        internal static string Error_Conflicto_FK {
            get {
                return ResourceManager.GetString("Error_Conflicto_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: el correo introducido ya se encuentra registrado.
        /// </summary>
        internal static string Error_Email_Existe {
            get {
                return ResourceManager.GetString("Error_Email_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reserva_M12.
        /// </summary>
        internal static string ExceptionM12 {
            get {
                return ResourceManager.GetString("ExceptionM12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fecha.
        /// </summary>
        internal static string FechaUsuario {
            get {
                return ResourceManager.GetString("FechaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha ingresado datos con un formato invalido.
        /// </summary>
        internal static string FormatoInvalido {
            get {
                return ResourceManager.GetString("FormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuID.
        /// </summary>
        internal static string IDUsuario {
            get {
                return ResourceManager.GetString("IDUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_ListarRoles.
        /// </summary>
        internal static string ListarRoles {
            get {
                return ResourceManager.GetString("ListarRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_ListarUsuarios.
        /// </summary>
        internal static string ListarUsuarios {
            get {
                return ResourceManager.GetString("ListarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Agregado Exitosamente.
        /// </summary>
        internal static string MensajeAgregado {
            get {
                return ResourceManager.GetString("MensajeAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Eliminado Exitosamente.
        /// </summary>
        internal static string MensajeEliminado {
            get {
                return ResourceManager.GetString("MensajeEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Modficado Exitosamente.
        /// </summary>
        internal static string MensajeModificado {
            get {
                return ResourceManager.GetString("MensajeModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status Cambiado Exitosamente.
        /// </summary>
        internal static string MensajeStatus {
            get {
                return ResourceManager.GetString("MensajeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_ModificarUsuario.
        /// </summary>
        internal static string ModificarUsuario {
            get {
                return ResourceManager.GetString("ModificarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string NombreUsuario {
            get {
                return ResourceManager.GetString("NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usunum.
        /// </summary>
        internal static string NumUsuario {
            get {
                return ResourceManager.GetString("NumUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al momento de realizar la operacion.
        /// </summary>
        internal static string OtroError {
            get {
                return ResourceManager.GetString("OtroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @activo.
        /// </summary>
        internal static string ParametroActivo {
            get {
                return ResourceManager.GetString("ParametroActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @apellido.
        /// </summary>
        internal static string ParametroApellido {
            get {
                return ResourceManager.GetString("ParametroApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @contraseña.
        /// </summary>
        internal static string ParametroContraseña {
            get {
                return ResourceManager.GetString("ParametroContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @correo.
        /// </summary>
        internal static string ParametroCorreo {
            get {
                return ResourceManager.GetString("ParametroCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fecha.
        /// </summary>
        internal static string ParametroFecha {
            get {
                return ResourceManager.GetString("ParametroFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @id.
        /// </summary>
        internal static string ParametroID {
            get {
                return ResourceManager.GetString("ParametroID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @nombre.
        /// </summary>
        internal static string ParametroNombre {
            get {
                return ResourceManager.GetString("ParametroNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rol.
        /// </summary>
        internal static string ParametroRolID {
            get {
                return ResourceManager.GetString("ParametroRolID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rolID.
        /// </summary>
        internal static string RolIDUsuario {
            get {
                return ResourceManager.GetString("RolIDUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rol.
        /// </summary>
        internal static string RolUsuario {
            get {
                return ResourceManager.GetString("RolUsuario", resourceCulture);
            }
        }
    }
}
