//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOReserva.Datos.Dao.gestion_reserva_automovil {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM19 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM19() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOReserva.Datos.Dao.gestion_reserva_automovil.RecursoDAOM19", typeof(RecursoDAOM19).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fk_lugar.
        /// </summary>
        internal static string fk_lugar {
            get {
                return ResourceManager.GetString("fk_lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @lug_id.
        /// </summary>
        internal static string lug_id {
            get {
                return ResourceManager.GetString("lug_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lug_id.
        /// </summary>
        internal static string LugarId {
            get {
                return ResourceManager.GetString("LugarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fk_lugar.
        /// </summary>
        internal static string LugarIdFk {
            get {
                return ResourceManager.GetString("LugarIdFk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lug_nombre.
        /// </summary>
        internal static string LugarNombre {
            get {
                return ResourceManager.GetString("LugarNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M10_ActualizarRestaurante.
        /// </summary>
        internal static string procedimientoActualizar {
            get {
                return ResourceManager.GetString("procedimientoActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M10_AgregarRestaurante.
        /// </summary>
        internal static string procedimientoAgregar {
            get {
                return ResourceManager.GetString("procedimientoAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M10_ConsultarRestaurante.
        /// </summary>
        internal static string procedimientoConsultar {
            get {
                return ResourceManager.GetString("procedimientoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M10_Consultar_Lugar.
        /// </summary>
        internal static string procedimientoConsultarLugar {
            get {
                return ResourceManager.GetString("procedimientoConsultarLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M10_ConsultarRestauranteId.
        /// </summary>
        internal static string procedimientoConsultarRestaurantId {
            get {
                return ResourceManager.GetString("procedimientoConsultarRestaurantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M10_EliminarRestaurante.
        /// </summary>
        internal static string procedimientoEliminar {
            get {
                return ResourceManager.GetString("procedimientoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rst_descripcion.
        /// </summary>
        internal static string restaurantDescripcion {
            get {
                return ResourceManager.GetString("restaurantDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rst_direccion.
        /// </summary>
        internal static string restaurantDireccion {
            get {
                return ResourceManager.GetString("restaurantDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rst_hora_apertura.
        /// </summary>
        internal static string restaurantHoraApertura {
            get {
                return ResourceManager.GetString("restaurantHoraApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rst_hora_cierre.
        /// </summary>
        internal static string restaurantHoraCierra {
            get {
                return ResourceManager.GetString("restaurantHoraCierra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rst_id.
        /// </summary>
        internal static string restaurantId {
            get {
                return ResourceManager.GetString("restaurantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rst_nombre.
        /// </summary>
        internal static string restaurantNombre {
            get {
                return ResourceManager.GetString("restaurantNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rst_telefono.
        /// </summary>
        internal static string restaurantTelefono {
            get {
                return ResourceManager.GetString("restaurantTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rst_descripcion.
        /// </summary>
        internal static string rst_descripcion {
            get {
                return ResourceManager.GetString("rst_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rst_direccion.
        /// </summary>
        internal static string rst_direccion {
            get {
                return ResourceManager.GetString("rst_direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rst_hora_apertura.
        /// </summary>
        internal static string rst_hora_apertura {
            get {
                return ResourceManager.GetString("rst_hora_apertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rst_hora_cierre.
        /// </summary>
        internal static string rst_hora_cierre {
            get {
                return ResourceManager.GetString("rst_hora_cierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rst_id.
        /// </summary>
        internal static string rst_id {
            get {
                return ResourceManager.GetString("rst_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rst_nombre.
        /// </summary>
        internal static string rst_nombre {
            get {
                return ResourceManager.GetString("rst_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rst_telefono.
        /// </summary>
        internal static string rst_telefono {
            get {
                return ResourceManager.GetString("rst_telefono", resourceCulture);
            }
        }
    }
}
