//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOReserva.DataAccess.DataAccessObject.M20 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM20 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM20() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOReserva.DataAccess.DataAccessObject.M20.RecursoDAOM20", typeof(RecursoDAOM20).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_FK_res_ref.
        /// </summary>
        internal static string parametroReferencia {
            get {
                return ResourceManager.GetString("parametroReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_fecha.
        /// </summary>
        internal static string parametroRevisionFecha {
            get {
                return ResourceManager.GetString("parametroRevisionFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_id.
        /// </summary>
        internal static string parametroRevisionID {
            get {
                return ResourceManager.GetString("parametroRevisionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_FK_res_hot_id.
        /// </summary>
        internal static string parametroRevisionIDReservaHabitacion {
            get {
                return ResourceManager.GetString("parametroRevisionIDReservaHabitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_FK_res_res_id.
        /// </summary>
        internal static string parametroRevisionIDReservaRestaurante {
            get {
                return ResourceManager.GetString("parametroRevisionIDReservaRestaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_FK_usu_id.
        /// </summary>
        internal static string parametroRevisionIDUsuario {
            get {
                return ResourceManager.GetString("parametroRevisionIDUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_mensaje.
        /// </summary>
        internal static string parametroRevisionMensaje {
            get {
                return ResourceManager.GetString("parametroRevisionMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_puntuacion.
        /// </summary>
        internal static string parametroRevisionPuntuacion {
            get {
                return ResourceManager.GetString("parametroRevisionPuntuacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_tipo.
        /// </summary>
        internal static string parametroRevisionTipo {
            get {
                return ResourceManager.GetString("parametroRevisionTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rv_fecha.
        /// </summary>
        internal static string parametroValaloracionFecha {
            get {
                return ResourceManager.GetString("parametroValaloracionFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rv_id.
        /// </summary>
        internal static string parametroValaloracionID {
            get {
                return ResourceManager.GetString("parametroValaloracionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rv_val_neg.
        /// </summary>
        internal static string parametroValaloracionNegativa {
            get {
                return ResourceManager.GetString("parametroValaloracionNegativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rv_val_pos.
        /// </summary>
        internal static string parametroValaloracionPositiva {
            get {
                return ResourceManager.GetString("parametroValaloracionPositiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rv_FK_rev.
        /// </summary>
        internal static string parametroValaloracionRevision {
            get {
                return ResourceManager.GetString("parametroValaloracionRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M20_GuardarRevision.
        /// </summary>
        internal static string procedimientoGuardarRevision {
            get {
                return ResourceManager.GetString("procedimientoGuardarRevision", resourceCulture);
            }
        }
    }
}
