//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOReserva.DataAccess.DataAccessObject.M20 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM20 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM20() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOReserva.DataAccess.DataAccessObject.M20.RecursoDAOM20", typeof(RecursoDAOM20).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_estrellas.
        /// </summary>
        internal static string parametroRevisionEstrellas {
            get {
                return ResourceManager.GetString("parametroRevisionEstrellas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_id.
        /// </summary>
        internal static string parametroRevisionId {
            get {
                return ResourceManager.GetString("parametroRevisionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_mensaje.
        /// </summary>
        internal static string parametroRevisionMensaje {
            get {
                return ResourceManager.GetString("parametroRevisionMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_fk_propietario.
        /// </summary>
        internal static string parametroRevisionPropietario {
            get {
                return ResourceManager.GetString("parametroRevisionPropietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_fk_referencia.
        /// </summary>
        internal static string parametroRevisionReferencia {
            get {
                return ResourceManager.GetString("parametroRevisionReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rev_tipo.
        /// </summary>
        internal static string parametroRevisionTipo {
            get {
                return ResourceManager.GetString("parametroRevisionTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to val_id.
        /// </summary>
        internal static string parametroValoracionId {
            get {
                return ResourceManager.GetString("parametroValoracionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to val_fk_propietario.
        /// </summary>
        internal static string parametroValoracionPropietario {
            get {
                return ResourceManager.GetString("parametroValoracionPropietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to val_punto.
        /// </summary>
        internal static string parametroValoracionPunto {
            get {
                return ResourceManager.GetString("parametroValoracionPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to val_fk_revision.
        /// </summary>
        internal static string parametroValoracionRevision {
            get {
                return ResourceManager.GetString("parametroValoracionRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M20_BorrarRevision.
        /// </summary>
        internal static string procedimientoBorrarRevision {
            get {
                return ResourceManager.GetString("procedimientoBorrarRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M20_GuardarRevision.
        /// </summary>
        internal static string procedimientoGuardarRevision {
            get {
                return ResourceManager.GetString("procedimientoGuardarRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M20_GuardarValoracion.
        /// </summary>
        internal static string procedimientoGuardarValoracion {
            get {
                return ResourceManager.GetString("procedimientoGuardarValoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M20_ObtenerRevisionesPorReferencia.
        /// </summary>
        internal static string procedimientoObtenerRevisionesPorReferencia {
            get {
                return ResourceManager.GetString("procedimientoObtenerRevisionesPorReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M20_ObtenerValoracionPorReferencia.
        /// </summary>
        internal static string procedimientoObtenerValoracionPorReferencia {
            get {
                return ResourceManager.GetString("procedimientoObtenerValoracionPorReferencia", resourceCulture);
            }
        }
    }
}
