//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOReserva.DataAccess.DataAccessObject.M14 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM14 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM14() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOReserva.DataAccess.DataAccessObject.M14.RecursoDAOM14", typeof(RecursoDAOM14).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_BuscarUsuario.
        /// </summary>
        internal static string M14_BuscarUsuario {
            get {
                return ResourceManager.GetString("M14_BuscarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_IniciarSesion.
        /// </summary>
        internal static string M14_IniciarSesion {
            get {
                return ResourceManager.GetString("M14_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ModificarClave.
        /// </summary>
        internal static string M14_ModificarClave {
            get {
                return ResourceManager.GetString("M14_ModificarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ModificarPerfil.
        /// </summary>
        internal static string M14_ModificarPerfil {
            get {
                return ResourceManager.GetString("M14_ModificarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @per_fecha_nacimiento.
        /// </summary>
        internal static string per_fecha_nacimiento {
            get {
                return ResourceManager.GetString("per_fecha_nacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @per_genero.
        /// </summary>
        internal static string per_genero {
            get {
                return ResourceManager.GetString("per_genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @per_id.
        /// </summary>
        internal static string per_id {
            get {
                return ResourceManager.GetString("per_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @pregunta1.
        /// </summary>
        internal static string pregunta1 {
            get {
                return ResourceManager.GetString("pregunta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @pregunta2.
        /// </summary>
        internal static string pregunta2 {
            get {
                return ResourceManager.GetString("pregunta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @pregunta3.
        /// </summary>
        internal static string pregunta3 {
            get {
                return ResourceManager.GetString("pregunta3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_AgregarUsuario.
        /// </summary>
        internal static string procedimientoAgregar {
            get {
                return ResourceManager.GetString("procedimientoAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ConsultarUsuario.
        /// </summary>
        internal static string procedimientoConsultarUsuario {
            get {
                return ResourceManager.GetString("procedimientoConsultarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_VerificarCorreo.
        /// </summary>
        internal static string procedimientoVerificarCorreo {
            get {
                return ResourceManager.GetString("procedimientoVerificarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @respuesta1.
        /// </summary>
        internal static string respuesta1 {
            get {
                return ResourceManager.GetString("respuesta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @respuesta2.
        /// </summary>
        internal static string respuesta2 {
            get {
                return ResourceManager.GetString("respuesta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @respuesta3.
        /// </summary>
        internal static string respuesta3 {
            get {
                return ResourceManager.GetString("respuesta3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_fk_rol.
        /// </summary>
        internal static string rolIdFk {
            get {
                return ResourceManager.GetString("rolIdFk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @tel_cod_area.
        /// </summary>
        internal static string tel_cod_area {
            get {
                return ResourceManager.GetString("tel_cod_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @tel_num_telefonico.
        /// </summary>
        internal static string tel_num_telefonico {
            get {
                return ResourceManager.GetString("tel_num_telefonico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_activo.
        /// </summary>
        internal static string usu_activo {
            get {
                return ResourceManager.GetString("usu_activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_apellido.
        /// </summary>
        internal static string usu_apellido {
            get {
                return ResourceManager.GetString("usu_apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_clave0.
        /// </summary>
        internal static string usu_clave0 {
            get {
                return ResourceManager.GetString("usu_clave0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_contraseña.
        /// </summary>
        internal static string usu_contraseña {
            get {
                return ResourceManager.GetString("usu_contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_correo.
        /// </summary>
        internal static string usu_correo {
            get {
                return ResourceManager.GetString("usu_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_fechaCreacion.
        /// </summary>
        internal static string usu_fechaCreacion {
            get {
                return ResourceManager.GetString("usu_fechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_fk_rol.
        /// </summary>
        internal static string usu_fk_rol {
            get {
                return ResourceManager.GetString("usu_fk_rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_id.
        /// </summary>
        internal static string usu_id {
            get {
                return ResourceManager.GetString("usu_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_nombre.
        /// </summary>
        internal static string usu_nombre {
            get {
                return ResourceManager.GetString("usu_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_apellido.
        /// </summary>
        internal static string usuarioApellido {
            get {
                return ResourceManager.GetString("usuarioApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tel_cod_area.
        /// </summary>
        internal static string usuarioCodArea {
            get {
                return ResourceManager.GetString("usuarioCodArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tel_cod_pais.
        /// </summary>
        internal static string usuarioCodPais {
            get {
                return ResourceManager.GetString("usuarioCodPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_contraseña.
        /// </summary>
        internal static string usuarioContrasena {
            get {
                return ResourceManager.GetString("usuarioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_correo.
        /// </summary>
        internal static string usuarioCorreo {
            get {
                return ResourceManager.GetString("usuarioCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_estado.
        /// </summary>
        internal static string usuarioEstado {
            get {
                return ResourceManager.GetString("usuarioEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_fechaCreacion.
        /// </summary>
        internal static string usuarioFechaCreacion {
            get {
                return ResourceManager.GetString("usuarioFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a per_genero.
        /// </summary>
        internal static string usuarioGenero {
            get {
                return ResourceManager.GetString("usuarioGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_id.
        /// </summary>
        internal static string usuarioId {
            get {
                return ResourceManager.GetString("usuarioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usu_nombre.
        /// </summary>
        internal static string usuarioNombre {
            get {
                return ResourceManager.GetString("usuarioNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tel_num_telefonico.
        /// </summary>
        internal static string usuarioTelefono {
            get {
                return ResourceManager.GetString("usuarioTelefono", resourceCulture);
            }
        }
    }
}
