//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOReserva.DataAccess.DataAccessObject.M14 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM14 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM14() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOReserva.DataAccess.DataAccessObject.M14.RecursoDAOM14", typeof(RecursoDAOM14).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_BuscarUsuario.
        /// </summary>
        internal static string M14_BuscarUsuario {
            get {
                return ResourceManager.GetString("M14_BuscarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_IniciarSesion.
        /// </summary>
        internal static string M14_IniciarSesion {
            get {
                return ResourceManager.GetString("M14_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ModificarPerfil.
        /// </summary>
        internal static string M14_ModificarPerfil {
            get {
                return ResourceManager.GetString("M14_ModificarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @per_fecha_nacimiento.
        /// </summary>
        internal static string per_fecha_nacimiento {
            get {
                return ResourceManager.GetString("per_fecha_nacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @per_genero.
        /// </summary>
        internal static string per_genero {
            get {
                return ResourceManager.GetString("per_genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @per_id.
        /// </summary>
        internal static string per_id {
            get {
                return ResourceManager.GetString("per_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pregunta1.
        /// </summary>
        internal static string pregunta1 {
            get {
                return ResourceManager.GetString("pregunta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pregunta2.
        /// </summary>
        internal static string pregunta2 {
            get {
                return ResourceManager.GetString("pregunta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pregunta3.
        /// </summary>
        internal static string pregunta3 {
            get {
                return ResourceManager.GetString("pregunta3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_AgregarUsuario.
        /// </summary>
        internal static string procedimientoAgregar {
            get {
                return ResourceManager.GetString("procedimientoAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ConsultarUsuario.
        /// </summary>
        internal static string procedimientoConsultarUsuario {
            get {
                return ResourceManager.GetString("procedimientoConsultarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_VerificarCorreo.
        /// </summary>
        internal static string procedimientoVerificarCorreo {
            get {
                return ResourceManager.GetString("procedimientoVerificarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @respuesta1.
        /// </summary>
        internal static string respuesta1 {
            get {
                return ResourceManager.GetString("respuesta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @respuesta2.
        /// </summary>
        internal static string respuesta2 {
            get {
                return ResourceManager.GetString("respuesta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @respuesta3.
        /// </summary>
        internal static string respuesta3 {
            get {
                return ResourceManager.GetString("respuesta3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_fk_rol.
        /// </summary>
        internal static string rolIdFk {
            get {
                return ResourceManager.GetString("rolIdFk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @tel_cod_area.
        /// </summary>
        internal static string tel_cod_area {
            get {
                return ResourceManager.GetString("tel_cod_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @tel_num_telefonico.
        /// </summary>
        internal static string tel_num_telefonico {
            get {
                return ResourceManager.GetString("tel_num_telefonico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usu_activo.
        /// </summary>
        internal static string usu_activo {
            get {
                return ResourceManager.GetString("usu_activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usu_apellido.
        /// </summary>
        internal static string usu_apellido {
            get {
                return ResourceManager.GetString("usu_apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usu_clave0.
        /// </summary>
        internal static string usu_clave0 {
            get {
                return ResourceManager.GetString("usu_clave0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usu_contraseña.
        /// </summary>
        internal static string usu_contraseña {
            get {
                return ResourceManager.GetString("usu_contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usu_correo.
        /// </summary>
        internal static string usu_correo {
            get {
                return ResourceManager.GetString("usu_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usu_fechaCreacion.
        /// </summary>
        internal static string usu_fechaCreacion {
            get {
                return ResourceManager.GetString("usu_fechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usu_fk_rol.
        /// </summary>
        internal static string usu_fk_rol {
            get {
                return ResourceManager.GetString("usu_fk_rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usu_id.
        /// </summary>
        internal static string usu_id {
            get {
                return ResourceManager.GetString("usu_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @usu_nombre.
        /// </summary>
        internal static string usu_nombre {
            get {
                return ResourceManager.GetString("usu_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_apellido.
        /// </summary>
        internal static string usuarioApellido {
            get {
                return ResourceManager.GetString("usuarioApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel_cod_area.
        /// </summary>
        internal static string usuarioCodArea {
            get {
                return ResourceManager.GetString("usuarioCodArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel_cod_pais.
        /// </summary>
        internal static string usuarioCodPais {
            get {
                return ResourceManager.GetString("usuarioCodPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_contraseña.
        /// </summary>
        internal static string usuarioContrasena {
            get {
                return ResourceManager.GetString("usuarioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_correo.
        /// </summary>
        internal static string usuarioCorreo {
            get {
                return ResourceManager.GetString("usuarioCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_estado.
        /// </summary>
        internal static string usuarioEstado {
            get {
                return ResourceManager.GetString("usuarioEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_fechaCreacion.
        /// </summary>
        internal static string usuarioFechaCreacion {
            get {
                return ResourceManager.GetString("usuarioFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per_genero.
        /// </summary>
        internal static string usuarioGenero {
            get {
                return ResourceManager.GetString("usuarioGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_id.
        /// </summary>
        internal static string usuarioId {
            get {
                return ResourceManager.GetString("usuarioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usu_nombre.
        /// </summary>
        internal static string usuarioNombre {
            get {
                return ResourceManager.GetString("usuarioNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel_num_telefonico.
        /// </summary>
        internal static string usuarioTelefono {
            get {
                return ResourceManager.GetString("usuarioTelefono", resourceCulture);
            }
        }
    }
}
