//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M02 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM02 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM02() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M02.RecursoDAOM02", typeof(RecursoDAOM02).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @avi_cap_equipaje.
        /// </summary>
        internal static string avi_cap_equipaje {
            get {
                return ResourceManager.GetString("avi_cap_equipaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @avi_disponibilidad.
        /// </summary>
        internal static string avi_disponibilidad {
            get {
                return ResourceManager.GetString("avi_disponibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @avi_id.
        /// </summary>
        internal static string avi_id {
            get {
                return ResourceManager.GetString("avi_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @avi_matricula.
        /// </summary>
        internal static string avi_matricula {
            get {
                return ResourceManager.GetString("avi_matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @avi_max_comb.
        /// </summary>
        internal static string avi_max_comb {
            get {
                return ResourceManager.GetString("avi_max_comb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @avi_max_dist.
        /// </summary>
        internal static string avi_max_dist {
            get {
                return ResourceManager.GetString("avi_max_dist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @avi_max_vel.
        /// </summary>
        internal static string avi_max_vel {
            get {
                return ResourceManager.GetString("avi_max_vel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @avi_modelo.
        /// </summary>
        internal static string avi_modelo {
            get {
                return ResourceManager.GetString("avi_modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @avi_pasajeros_ejecutiva.
        /// </summary>
        internal static string avi_pasajeros_ejecutiva {
            get {
                return ResourceManager.GetString("avi_pasajeros_ejecutiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @avi_pasajeros_turista.
        /// </summary>
        internal static string avi_pasajeros_turista {
            get {
                return ResourceManager.GetString("avi_pasajeros_turista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @avi_pasajeros_vip.
        /// </summary>
        internal static string avi_pasajeros_vip {
            get {
                return ResourceManager.GetString("avi_pasajeros_vip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M02_AgregarAvion.
        /// </summary>
        internal static string ProcedimientoAgregarAvion {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarAvion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M02_ConsultarAvion.
        /// </summary>
        internal static string ProcedimientoConsultarAvion {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarAvion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M02_ConsultarID.
        /// </summary>
        internal static string ProcedimientoConsultarID {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M02_Disponibilidad.
        /// </summary>
        internal static string ProcedimientoDisponibilidad {
            get {
                return ResourceManager.GetString("ProcedimientoDisponibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M02_EliminarAvion.
        /// </summary>
        internal static string ProcedimientoEliminarAvion {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarAvion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M02_ModificarAvion.
        /// </summary>
        internal static string ProcedimientoModificarAvion {
            get {
                return ResourceManager.GetString("ProcedimientoModificarAvion", resourceCulture);
            }
        }
    }
}
