//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOReserva.DataAccess.DataAccessObject.M19 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM19 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM19() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOReserva.DataAccess.DataAccessObject.M19.RecursoDAOM19", typeof(RecursoDAOM19).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_anio.
        /// </summary>
        internal static string autAnio {
            get {
                return ResourceManager.GetString("autAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_cantpasajeros.
        /// </summary>
        internal static string autCantpasajeros {
            get {
                return ResourceManager.GetString("autCantpasajeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_color.
        /// </summary>
        internal static string autColor {
            get {
                return ResourceManager.GetString("autColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_disponibilidad.
        /// </summary>
        internal static string autDisponibilidad {
            get {
                return ResourceManager.GetString("autDisponibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_fabricante.
        /// </summary>
        internal static string autFabricante {
            get {
                return ResourceManager.GetString("autFabricante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_fecharegistro.
        /// </summary>
        internal static string autFecharegistro {
            get {
                return ResourceManager.GetString("autFecharegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_fk_ciudad.
        /// </summary>
        internal static string autFk_ciudad {
            get {
                return ResourceManager.GetString("autFk_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_kilometraje.
        /// </summary>
        internal static string autKilometraje {
            get {
                return ResourceManager.GetString("autKilometraje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_matricula.
        /// </summary>
        internal static string autMatricula {
            get {
                return ResourceManager.GetString("autMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_modelo.
        /// </summary>
        internal static string autModelo {
            get {
                return ResourceManager.GetString("autModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_penalidaddiaria.
        /// </summary>
        internal static string autPenalidaddiaria {
            get {
                return ResourceManager.GetString("autPenalidaddiaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_precioalquiler.
        /// </summary>
        internal static string autPrecioalquiler {
            get {
                return ResourceManager.GetString("autPrecioalquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_preciocompra.
        /// </summary>
        internal static string autPreciocompra {
            get {
                return ResourceManager.GetString("autPreciocompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_tipovehiculo.
        /// </summary>
        internal static string autTipo {
            get {
                return ResourceManager.GetString("autTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_transmision.
        /// </summary>
        internal static string autTransmision {
            get {
                return ResourceManager.GetString("autTransmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destino.
        /// </summary>
        internal static string destino {
            get {
                return ResourceManager.GetString("destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_lugar.
        /// </summary>
        internal static string fk_lugar {
            get {
                return ResourceManager.GetString("fk_lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @lug_id.
        /// </summary>
        internal static string lug_id {
            get {
                return ResourceManager.GetString("lug_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lug_id.
        /// </summary>
        internal static string LugarId {
            get {
                return ResourceManager.GetString("LugarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fk_lugar.
        /// </summary>
        internal static string LugarIdFk {
            get {
                return ResourceManager.GetString("LugarIdFk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lug_nombre.
        /// </summary>
        internal static string LugarNombre {
            get {
                return ResourceManager.GetString("LugarNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de Casteo.
        /// </summary>
        internal static string MensajeErrorFormato {
            get {
                return ResourceManager.GetString("MensajeErrorFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida del Método.
        /// </summary>
        internal static string MensajeFinMetodoLogger {
            get {
                return ResourceManager.GetString("MensajeFinMetodoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada en el Método.
        /// </summary>
        internal static string MensajeInicioMetodoLogger {
            get {
                return ResourceManager.GetString("MensajeInicioMetodoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to origen.
        /// </summary>
        internal static string origen {
            get {
                return ResourceManager.GetString("origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M19_ActualizarReservaAutomovil.
        /// </summary>
        internal static string procedimientoActualizar {
            get {
                return ResourceManager.GetString("procedimientoActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M19_AgregarReservaAutomovil.
        /// </summary>
        internal static string procedimientoAgregar {
            get {
                return ResourceManager.GetString("procedimientoAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M19_ConsultarReservaAutomovil.
        /// </summary>
        internal static string procedimientoConsultar {
            get {
                return ResourceManager.GetString("procedimientoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M19_ConsultarReservaAPorCiudad.
        /// </summary>
        internal static string procedimientoConsultarACiudad {
            get {
                return ResourceManager.GetString("procedimientoConsultarACiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M19_ConsultarReservaAutomovilPorCiudad.
        /// </summary>
        internal static string procedimientoConsultarAutosCiudad {
            get {
                return ResourceManager.GetString("procedimientoConsultarAutosCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M19_Consultar_Lugar.
        /// </summary>
        internal static string procedimientoConsultarLugar {
            get {
                return ResourceManager.GetString("procedimientoConsultarLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M19_ConsultarReservaAutomovilId.
        /// </summary>
        internal static string procedimientoConsultarReservaAutomovilId {
            get {
                return ResourceManager.GetString("procedimientoConsultarReservaAutomovilId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M19_EliminarReservaAutomovil.
        /// </summary>
        internal static string procedimientoEliminar {
            get {
                return ResourceManager.GetString("procedimientoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @raut_estatus.
        /// </summary>
        internal static string raut_estatus {
            get {
                return ResourceManager.GetString("raut_estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @raut_fecha_fin.
        /// </summary>
        internal static string raut_fecha_fin {
            get {
                return ResourceManager.GetString("raut_fecha_fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @raut_fecha_ini.
        /// </summary>
        internal static string raut_fecha_ini {
            get {
                return ResourceManager.GetString("raut_fecha_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @raut_fk_automovil.
        /// </summary>
        internal static string raut_fk_automovil {
            get {
                return ResourceManager.GetString("raut_fk_automovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @raut_fk_ciudad_devolucion.
        /// </summary>
        internal static string raut_fk_ciudad_devolucion {
            get {
                return ResourceManager.GetString("raut_fk_ciudad_devolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @raut_fk_ciudad_entrega.
        /// </summary>
        internal static string raut_fk_ciudad_entrega {
            get {
                return ResourceManager.GetString("raut_fk_ciudad_entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @raut_fk_usuario.
        /// </summary>
        internal static string raut_fk_usuario {
            get {
                return ResourceManager.GetString("raut_fk_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @raut_hora_fin.
        /// </summary>
        internal static string raut_hora_fin {
            get {
                return ResourceManager.GetString("raut_hora_fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @raut_hora_ini.
        /// </summary>
        internal static string raut_hora_ini {
            get {
                return ResourceManager.GetString("raut_hora_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @raut_id.
        /// </summary>
        internal static string raut_id {
            get {
                return ResourceManager.GetString("raut_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raut_fk_automovil.
        /// </summary>
        internal static string reservaAutomovilFk {
            get {
                return ResourceManager.GetString("reservaAutomovilFk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raut_fk_ciudad_devolucion.
        /// </summary>
        internal static string reservaCiudadDevFk {
            get {
                return ResourceManager.GetString("reservaCiudadDevFk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raut_fk_ciudad_entrega.
        /// </summary>
        internal static string reservaCiudadEntFk {
            get {
                return ResourceManager.GetString("reservaCiudadEntFk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raut_estatus.
        /// </summary>
        internal static string reservaEstatus {
            get {
                return ResourceManager.GetString("reservaEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raut_fecha_fin.
        /// </summary>
        internal static string reservaFechaFin {
            get {
                return ResourceManager.GetString("reservaFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raut_fecha_ini.
        /// </summary>
        internal static string reservaFechaIni {
            get {
                return ResourceManager.GetString("reservaFechaIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raut_hora_fin.
        /// </summary>
        internal static string reservaHoraFin {
            get {
                return ResourceManager.GetString("reservaHoraFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raut_hora_ini.
        /// </summary>
        internal static string reservaHoraIni {
            get {
                return ResourceManager.GetString("reservaHoraIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raut_id.
        /// </summary>
        internal static string reservaId {
            get {
                return ResourceManager.GetString("reservaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raut_fk_usuario.
        /// </summary>
        internal static string reservaUsuarioFk {
            get {
                return ResourceManager.GetString("reservaUsuarioFk", resourceCulture);
            }
        }
    }
}
