//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOReserva.DataAccess.DataAccessObject.M19 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM19 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM19() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOReserva.DataAccess.DataAccessObject.M19.RecursoDAOM19", typeof(RecursoDAOM19).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_anio.
        /// </summary>
        internal static string autAnio {
            get {
                return ResourceManager.GetString("autAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_cantpasajeros.
        /// </summary>
        internal static string autCantpasajeros {
            get {
                return ResourceManager.GetString("autCantpasajeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_color.
        /// </summary>
        internal static string autColor {
            get {
                return ResourceManager.GetString("autColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_disponibilidad.
        /// </summary>
        internal static string autDisponibilidad {
            get {
                return ResourceManager.GetString("autDisponibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_fabricante.
        /// </summary>
        internal static string autFabricante {
            get {
                return ResourceManager.GetString("autFabricante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_fecharegistro.
        /// </summary>
        internal static string autFecharegistro {
            get {
                return ResourceManager.GetString("autFecharegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_fk_ciudad.
        /// </summary>
        internal static string autFk_ciudad {
            get {
                return ResourceManager.GetString("autFk_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_kilometraje.
        /// </summary>
        internal static string autKilometraje {
            get {
                return ResourceManager.GetString("autKilometraje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_matricula.
        /// </summary>
        internal static string autMatricula {
            get {
                return ResourceManager.GetString("autMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_modelo.
        /// </summary>
        internal static string autModelo {
            get {
                return ResourceManager.GetString("autModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_penalidaddiaria.
        /// </summary>
        internal static string autPenalidaddiaria {
            get {
                return ResourceManager.GetString("autPenalidaddiaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_precioalquiler.
        /// </summary>
        internal static string autPrecioalquiler {
            get {
                return ResourceManager.GetString("autPrecioalquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_preciocompra.
        /// </summary>
        internal static string autPreciocompra {
            get {
                return ResourceManager.GetString("autPreciocompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_tipo.
        /// </summary>
        internal static string autTipo {
            get {
                return ResourceManager.GetString("autTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aut_transmision.
        /// </summary>
        internal static string autTransmision {
            get {
                return ResourceManager.GetString("autTransmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a destino.
        /// </summary>
        internal static string destino {
            get {
                return ResourceManager.GetString("destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fk_lugar.
        /// </summary>
        internal static string fk_lugar {
            get {
                return ResourceManager.GetString("fk_lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @lug_id.
        /// </summary>
        internal static string lug_id {
            get {
                return ResourceManager.GetString("lug_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lug_id.
        /// </summary>
        internal static string LugarId {
            get {
                return ResourceManager.GetString("LugarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fk_lugar.
        /// </summary>
        internal static string LugarIdFk {
            get {
                return ResourceManager.GetString("LugarIdFk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lug_nombre.
        /// </summary>
        internal static string LugarNombre {
            get {
                return ResourceManager.GetString("LugarNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a origen.
        /// </summary>
        internal static string origen {
            get {
                return ResourceManager.GetString("origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M19_ActualizarReservaAutomovil.
        /// </summary>
        internal static string procedimientoActualizar {
            get {
                return ResourceManager.GetString("procedimientoActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M19_AgregarReservaAutomovil.
        /// </summary>
        internal static string procedimientoAgregar {
            get {
                return ResourceManager.GetString("procedimientoAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M19_ConsultarReservaAutomovil.
        /// </summary>
        internal static string procedimientoConsultar {
            get {
                return ResourceManager.GetString("procedimientoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M19_ConsultarReservaAutomovilPorCiudad.
        /// </summary>
        internal static string procedimientoConsultarAutosCiudad {
            get {
                return ResourceManager.GetString("procedimientoConsultarAutosCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M19_Consultar_Lugar.
        /// </summary>
        internal static string procedimientoConsultarLugar {
            get {
                return ResourceManager.GetString("procedimientoConsultarLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M19_ConsultarReservaAutomovilId.
        /// </summary>
        internal static string procedimientoConsultarReservaAutomovilId {
            get {
                return ResourceManager.GetString("procedimientoConsultarReservaAutomovilId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M19_EliminarReservaAutomovil.
        /// </summary>
        internal static string procedimientoEliminar {
            get {
                return ResourceManager.GetString("procedimientoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @raut_estatus.
        /// </summary>
        internal static string raut_estatus {
            get {
                return ResourceManager.GetString("raut_estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @raut_fecha_fin.
        /// </summary>
        internal static string raut_fecha_fin {
            get {
                return ResourceManager.GetString("raut_fecha_fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @raut_fecha_ini.
        /// </summary>
        internal static string raut_fecha_ini {
            get {
                return ResourceManager.GetString("raut_fecha_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @raut_fk_automovil.
        /// </summary>
        internal static string raut_fk_automovil {
            get {
                return ResourceManager.GetString("raut_fk_automovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @raut_fk_ciudad_devolucion.
        /// </summary>
        internal static string raut_fk_ciudad_devolucion {
            get {
                return ResourceManager.GetString("raut_fk_ciudad_devolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @raut_fk_ciudad_entrega.
        /// </summary>
        internal static string raut_fk_ciudad_entrega {
            get {
                return ResourceManager.GetString("raut_fk_ciudad_entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @raut_fk_usuario.
        /// </summary>
        internal static string raut_fk_usuario {
            get {
                return ResourceManager.GetString("raut_fk_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @raut_hora_fin.
        /// </summary>
        internal static string raut_hora_fin {
            get {
                return ResourceManager.GetString("raut_hora_fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @raut_hora_ini.
        /// </summary>
        internal static string raut_hora_ini {
            get {
                return ResourceManager.GetString("raut_hora_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @raut_id.
        /// </summary>
        internal static string raut_id {
            get {
                return ResourceManager.GetString("raut_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a raut_fk_automovil.
        /// </summary>
        internal static string reservaAutomovilFk {
            get {
                return ResourceManager.GetString("reservaAutomovilFk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a raut_fk_ciudad_devolucion.
        /// </summary>
        internal static string reservaCiudadDevFk {
            get {
                return ResourceManager.GetString("reservaCiudadDevFk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a raut_fk_ciudad_entrega.
        /// </summary>
        internal static string reservaCiudadEntFk {
            get {
                return ResourceManager.GetString("reservaCiudadEntFk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a raut_estatus.
        /// </summary>
        internal static string reservaEstatus {
            get {
                return ResourceManager.GetString("reservaEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a raut_fecha_fin.
        /// </summary>
        internal static string reservaFechaFin {
            get {
                return ResourceManager.GetString("reservaFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a raut_fecha_ini.
        /// </summary>
        internal static string reservaFechaIni {
            get {
                return ResourceManager.GetString("reservaFechaIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a raut_hora_fin.
        /// </summary>
        internal static string reservaHoraFin {
            get {
                return ResourceManager.GetString("reservaHoraFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a raut_hora_ini.
        /// </summary>
        internal static string reservaHoraIni {
            get {
                return ResourceManager.GetString("reservaHoraIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a raut_id.
        /// </summary>
        internal static string reservaId {
            get {
                return ResourceManager.GetString("reservaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a raut_fk_usuario.
        /// </summary>
        internal static string reservaUsuarioFk {
            get {
                return ResourceManager.GetString("reservaUsuarioFk", resourceCulture);
            }
        }
    }
}
