//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M13 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class M13_DAOResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M13_DAOResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M13.M13_DAOResources", typeof(M13_DAOResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_AgregarPermisosRol.
        /// </summary>
        internal static string AgregarPermisoRol {
            get {
                return ResourceManager.GetString("AgregarPermisoRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_AgregarRol.
        /// </summary>
        internal static string AgregarRol {
            get {
                return ResourceManager.GetString("AgregarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_ConsultarPermisos.
        /// </summary>
        internal static string ConsultarPermisos {
            get {
                return ResourceManager.GetString("ConsultarPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_ConsultarPermisosAsociados.
        /// </summary>
        internal static string ConsultarPermisosAsociados {
            get {
                return ResourceManager.GetString("ConsultarPermisosAsociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_ConsultarPermisosNoAsociados.
        /// </summary>
        internal static string ConsultarPermisosNoAsociados {
            get {
                return ResourceManager.GetString("ConsultarPermisosNoAsociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_ConsultarPermisosUsuario.
        /// </summary>
        internal static string ConsultarPermisosUsuario {
            get {
                return ResourceManager.GetString("ConsultarPermisosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_ConsultarRol.
        /// </summary>
        internal static string ConsultarRol {
            get {
                return ResourceManager.GetString("ConsultarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_ConsultarRoles.
        /// </summary>
        internal static string ConsultarRoles {
            get {
                return ResourceManager.GetString("ConsultarRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_EliminarPermisos.
        /// </summary>
        internal static string EliminarPermisos {
            get {
                return ResourceManager.GetString("EliminarPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_EliminarRol.
        /// </summary>
        internal static string EliminarRol {
            get {
                return ResourceManager.GetString("EliminarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_ListarPermisos.
        /// </summary>
        internal static string ListarPermisos {
            get {
                return ResourceManager.GetString("ListarPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_QuitarPermiso.
        /// </summary>
        internal static string QuitarPermiso {
            get {
                return ResourceManager.GetString("QuitarPermiso", resourceCulture);
            }
        }
    }
}
