//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M12 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM12 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM12() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M12.RecursoDAOM12", typeof(RecursoDAOM12).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id_rol.
        /// </summary>
        internal static string id_rol {
            get {
                return ResourceManager.GetString("id_rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre_rol.
        /// </summary>
        internal static string nombre_rol {
            get {
                return ResourceManager.GetString("nombre_rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_AgregarUsuario.
        /// </summary>
        internal static string ProcedimientoAgregarUsuario {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_BorrarUsuario.
        /// </summary>
        internal static string ProcedimientoBorrarUsuario {
            get {
                return ResourceManager.GetString("ProcedimientoBorrarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_EditarUsuario.
        /// </summary>
        internal static string ProcedimientoEditarUsuario {
            get {
                return ResourceManager.GetString("ProcedimientoEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_StatusUsuario.
        /// </summary>
        internal static string ProcedimientoStatusUsuario {
            get {
                return ResourceManager.GetString("ProcedimientoStatusUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_VisualizarUnUsuario.
        /// </summary>
        internal static string ProcedimientoVisualizarUnUsuario {
            get {
                return ResourceManager.GetString("ProcedimientoVisualizarUnUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M12_VisualizarUsuario.
        /// </summary>
        internal static string ProcedimientoVisualizarUsuario {
            get {
                return ResourceManager.GetString("ProcedimientoVisualizarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_activo.
        /// </summary>
        internal static string usu_activo {
            get {
                return ResourceManager.GetString("usu_activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_apellido.
        /// </summary>
        internal static string usu_apellido {
            get {
                return ResourceManager.GetString("usu_apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_contraseña.
        /// </summary>
        internal static string usu_contraseña {
            get {
                return ResourceManager.GetString("usu_contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_correo.
        /// </summary>
        internal static string usu_correo {
            get {
                return ResourceManager.GetString("usu_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_fechaCreacion.
        /// </summary>
        internal static string usu_fechaCreacion {
            get {
                return ResourceManager.GetString("usu_fechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_fk_rol.
        /// </summary>
        internal static string usu_fk_rol {
            get {
                return ResourceManager.GetString("usu_fk_rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_id.
        /// </summary>
        internal static string usu_id {
            get {
                return ResourceManager.GetString("usu_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usu_nombre.
        /// </summary>
        internal static string usu_nombre {
            get {
                return ResourceManager.GetString("usu_nombre", resourceCulture);
            }
        }
    }
}
