//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M08 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM08 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM08() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M08.RecursoDAOM08", typeof(RecursoDAOM08).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_lugar.
        /// </summary>
        internal static string fk_lugar {
            get {
                return ResourceManager.GetString("fk_lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @lug_id.
        /// </summary>
        internal static string lug_id {
            get {
                return ResourceManager.GetString("lug_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lug_id.
        /// </summary>
        internal static string LugarId {
            get {
                return ResourceManager.GetString("LugarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fk_lugar.
        /// </summary>
        internal static string LugarIdFk {
            get {
                return ResourceManager.GetString("LugarIdFk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lug_nombre.
        /// </summary>
        internal static string LugarNombre {
            get {
                return ResourceManager.GetString("LugarNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M08_AgregarAutomovil.
        /// </summary>
        internal static string procedimientoAgregar {
            get {
                return ResourceManager.GetString("procedimientoAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M08_Consultar_Automovil.
        /// </summary>
        internal static string procedimientoConsultarAutomovil {
            get {
                return ResourceManager.GetString("procedimientoConsultarAutomovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M08_Consultar_Lugar.
        /// </summary>
        internal static string procedimientoConsultarLugar {
            get {
                return ResourceManager.GetString("procedimientoConsultarLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M08_ModificarAutomovil.
        /// </summary>
        internal static string procedimientoModificar {
            get {
                return ResourceManager.GetString("procedimientoModificar", resourceCulture);
            }
        }
    }
}
