//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOReserva.DataAccess.DataAccessObject.M08 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM08 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        internal static string procedimientoCambiarEstatus;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM08() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOReserva.DataAccess.DataAccessObject.M08.RecursoDAOM08", typeof(RecursoDAOM08).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_anio.
        /// </summary>
        internal static string anio {
            get {
                return ResourceManager.GetString("anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_anio.
        /// </summary>
        internal static string aut_anio {
            get {
                return ResourceManager.GetString("aut_anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_cantpasajero.
        /// </summary>
        internal static string aut_cantpasajero {
            get {
                return ResourceManager.GetString("aut_cantpasajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_color.
        /// </summary>
        internal static string aut_color {
            get {
                return ResourceManager.GetString("aut_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_disponibilida.
        /// </summary>
        internal static string aut_disponibilida {
            get {
                return ResourceManager.GetString("aut_disponibilida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_fabricante.
        /// </summary>
        internal static string aut_fabricante {
            get {
                return ResourceManager.GetString("aut_fabricante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_fecharegistro.
        /// </summary>
        internal static string aut_fecharegistro {
            get {
                return ResourceManager.GetString("aut_fecharegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_fk_ciudad.
        /// </summary>
        internal static string aut_fk_ciudad {
            get {
                return ResourceManager.GetString("aut_fk_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_kilometraje.
        /// </summary>
        internal static string aut_kilometraje {
            get {
                return ResourceManager.GetString("aut_kilometraje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_matricula.
        /// </summary>
        internal static string aut_matricula {
            get {
                return ResourceManager.GetString("aut_matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_modelo.
        /// </summary>
        internal static string aut_modelo {
            get {
                return ResourceManager.GetString("aut_modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_penalidaddiaria.
        /// </summary>
        internal static string aut_penalidaddiaria {
            get {
                return ResourceManager.GetString("aut_penalidaddiaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_precioalquiler.
        /// </summary>
        internal static string aut_precioalquiler {
            get {
                return ResourceManager.GetString("aut_precioalquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_preciocompra.
        /// </summary>
        internal static string aut_preciocompra {
            get {
                return ResourceManager.GetString("aut_preciocompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_tipovehiculo.
        /// </summary>
        internal static string aut_tipovehiculo {
            get {
                return ResourceManager.GetString("aut_tipovehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @aut_transmision.
        /// </summary>
        internal static string aut_transmision {
            get {
                return ResourceManager.GetString("aut_transmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_cantpasajero.
        /// </summary>
        internal static string cantpasajero {
            get {
                return ResourceManager.GetString("cantpasajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_color.
        /// </summary>
        internal static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_disponibilida.
        /// </summary>
        internal static string disponibilida {
            get {
                return ResourceManager.GetString("disponibilida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_fabricante.
        /// </summary>
        internal static string fabricante {
            get {
                return ResourceManager.GetString("fabricante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_fecharegistro.
        /// </summary>
        internal static string fecharegistro {
            get {
                return ResourceManager.GetString("fecharegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_fk_ciudad.
        /// </summary>
        internal static string fk_ciudad {
            get {
                return ResourceManager.GetString("fk_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_kilometraje.
        /// </summary>
        internal static string kilometraje {
            get {
                return ResourceManager.GetString("kilometraje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_matricula.
        /// </summary>
        internal static string matricula {
            get {
                return ResourceManager.GetString("matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_modelo.
        /// </summary>
        internal static string modelo {
            get {
                return ResourceManager.GetString("modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_penalidaddiaria.
        /// </summary>
        internal static string penalidaddiaria {
            get {
                return ResourceManager.GetString("penalidaddiaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_precioalquiler.
        /// </summary>
        internal static string precioalquiler {
            get {
                return ResourceManager.GetString("precioalquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_preciocompra.
        /// </summary>
        internal static string preciocompra {
            get {
                return ResourceManager.GetString("preciocompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M08_AgregarAutomovil.
        /// </summary>
        internal static string procedimientoAgregarAutomovil {
            get {
                return ResourceManager.GetString("procedimientoAgregarAutomovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M08_Consultar_Automovil.
        /// </summary>
        internal static string procedimientoConsultarAutomovil {
            get {
                return ResourceManager.GetString("procedimientoConsultarAutomovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M08_ConsultarAutomovilMatricula.
        /// </summary>
        internal static string procedimientoConsultarAutomovilMatricula {
            get {
                return ResourceManager.GetString("procedimientoConsultarAutomovilMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M08_Consultar_Lugar.
        /// </summary>
        internal static string procedimientoConsultarLugar {
            get {
                return ResourceManager.GetString("procedimientoConsultarLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M08_EliminarAutomovil.
        /// </summary>
        internal static string procedimientoEliminarAutomovil {
            get {
                return ResourceManager.GetString("procedimientoEliminarAutomovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M08_ModificarAutomovil.
        /// </summary>
        internal static string procedimientoModificar {
            get {
                return ResourceManager.GetString("procedimientoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_tipovehiculo.
        /// </summary>
        internal static string tipovehiculo {
            get {
                return ResourceManager.GetString("tipovehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut_transmision.
        /// </summary>
        internal static string transmision {
            get {
                return ResourceManager.GetString("transmision", resourceCulture);
            }
        }

        public static string procedimientoModificarAutomovil { get; internal set; }

        public static System.Data.DataColumn pais { get; set; }

        public static System.Data.DataColumn ciudad { get; set; }

        public static string MensajeInicioMetodoLogger { get; set; }

        public static string MensajeFinMetodoLogger { get; set; }

        public static string MensajeErrorFormato { get; set; }
        public static string disponibilidad { get; internal set; }

        public static string procedimientoExisteMatriculaAutomovil { get; set; }
    }
}
