//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOReserva.DataAccess.DataAccessObject.M22Cruceros {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOReservaCrucero {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOReservaCrucero() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOReserva.DataAccess.DataAccessObject.M22Cruceros.RecursoDAOReservaCrucero", typeof(RecursoDAOReservaCrucero).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @cantidadPasajeros.
        /// </summary>
        internal static string cantidadPasajeros {
            get {
                return ResourceManager.GetString("cantidadPasajeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cru_id.
        /// </summary>
        internal static string cru_id {
            get {
                return ResourceManager.GetString("cru_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cru_nombre.
        /// </summary>
        internal static string cru_nombre {
            get {
                return ResourceManager.GetString("cru_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @crucero.
        /// </summary>
        internal static string crucero {
            get {
                return ResourceManager.GetString("crucero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fechaInicio.
        /// </summary>
        internal static string fechaInicio {
            get {
                return ResourceManager.GetString("fechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fechaReserva.
        /// </summary>
        internal static string fechaReserva {
            get {
                return ResourceManager.GetString("fechaReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fechaVuelta.
        /// </summary>
        internal static string fechaVuelta {
            get {
                return ResourceManager.GetString("fechaVuelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @cru_id.
        /// </summary>
        internal static string id_crucero {
            get {
                return ResourceManager.GetString("id_crucero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @id_reserva.
        /// </summary>
        internal static string id_reserva {
            get {
                return ResourceManager.GetString("id_reserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_AgregarReservaCrucero.
        /// </summary>
        internal static string ProcedimientoAgregarReserva {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_BuscarCruceros.
        /// </summary>
        internal static string ProcedimientoBuscarCruceros {
            get {
                return ResourceManager.GetString("ProcedimientoBuscarCruceros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_BuscarItinerarios.
        /// </summary>
        internal static string ProcedimientoBuscarItinerarios {
            get {
                return ResourceManager.GetString("ProcedimientoBuscarItinerarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_BuscarCrucerosPerfil.
        /// </summary>
        internal static string ProcedimientoCrucerosPerfil {
            get {
                return ResourceManager.GetString("ProcedimientoCrucerosPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_EliminarReserva.
        /// </summary>
        internal static string ProcedimientoEliminarReserva {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_ModificarReserva.
        /// </summary>
        internal static string ProcedimientoModificarReserva {
            get {
                return ResourceManager.GetString("ProcedimientoModificarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ruta.
        /// </summary>
        internal static string ruta {
            get {
                return ResourceManager.GetString("ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @usuario.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
    }
}
