//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOReserva.DataAccess.DataAccessObject.M22 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursoDAOM22 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursoDAOM22() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOReserva.DataAccess.DataAccessObject.M22.RecursoDAOM22", typeof(RecursoDAOM22).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cant_habitaciones.
        /// </summary>
        internal static string cant_habitaciones {
            get {
                return ResourceManager.GetString("cant_habitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hot_fk_ciudad.
        /// </summary>
        internal static string hot_fk_ciudad {
            get {
                return ResourceManager.GetString("hot_fk_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id_habitacion.
        /// </summary>
        internal static string id_habitacion {
            get {
                return ResourceManager.GetString("id_habitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id_hotel.
        /// </summary>
        internal static string id_hotel {
            get {
                return ResourceManager.GetString("id_hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id_lugar.
        /// </summary>
        internal static string id_lugar {
            get {
                return ResourceManager.GetString("id_lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id_usuario.
        /// </summary>
        internal static string id_usuario {
            get {
                return ResourceManager.GetString("id_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre_hotel.
        /// </summary>
        internal static string nombre_hotel {
            get {
                return ResourceManager.GetString("nombre_hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre_lugar.
        /// </summary>
        internal static string nombre_lugar {
            get {
                return ResourceManager.GetString("nombre_lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre_usuario.
        /// </summary>
        internal static string nombre_usuario {
            get {
                return ResourceManager.GetString("nombre_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_AgregarReservaHabitacion.
        /// </summary>
        internal static string ProcedimientoAgregarReservaHabitacion {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarReservaHabitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_ConsultarHotelesPorCiudad.
        /// </summary>
        internal static string ProcedimientoConsultarHotelesPorCiudad {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarHotelesPorCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_ConsultarReservaHabitacion.
        /// </summary>
        internal static string ProcedimientoConsultarReservaHabitacion {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarReservaHabitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_ConsultarReservasHabitacion.
        /// </summary>
        internal static string ProcedimientoConsultarTodos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_EliminarReservaHabitacion.
        /// </summary>
        internal static string ProcedimientoEliminarReservaHabitacion {
            get {
                return ResourceManager.GetString("ProcedimientoEliminarReservaHabitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_ListarCiudades.
        /// </summary>
        internal static string ProcedimientoListarCiudades {
            get {
                return ResourceManager.GetString("ProcedimientoListarCiudades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M22_ModificarReservaHabitacion.
        /// </summary>
        internal static string ProcedimientoModificarReservaHabitacion {
            get {
                return ResourceManager.GetString("ProcedimientoModificarReservaHabitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rha_cantidad.
        /// </summary>
        internal static string rha_cantidad_dias {
            get {
                return ResourceManager.GetString("rha_cantidad_dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rha_estatus.
        /// </summary>
        internal static string rha_estado {
            get {
                return ResourceManager.GetString("rha_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rha_fecha_lleg.
        /// </summary>
        internal static string rha_fecha_llegada {
            get {
                return ResourceManager.GetString("rha_fecha_llegada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rha_fecha_res.
        /// </summary>
        internal static string rha_fecha_reservacion {
            get {
                return ResourceManager.GetString("rha_fecha_reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rha_fk_hab.
        /// </summary>
        internal static string rha_fk_hab_id {
            get {
                return ResourceManager.GetString("rha_fk_hab_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rha_fk_usu.
        /// </summary>
        internal static string rha_fk_usu_id {
            get {
                return ResourceManager.GetString("rha_fk_usu_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @rha_id.
        /// </summary>
        internal static string rha_id {
            get {
                return ResourceManager.GetString("rha_id", resourceCulture);
            }
        }
    }
}
